# Generated by Django 4.2.10 on 2025-03-13 21:35

import django.core.validators
from django.db import migrations, models
import plate_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=3, verbose_name='Código da Empresa')),
                ('projeto', models.CharField(max_length=10, verbose_name='Código do Projeto')),
                ('total_amostras', models.IntegerField(validators=[django.core.validators.MinValueValidator(1500, message='O número mínimo de amostras é 1500.'), django.core.validators.MaxValueValidator(40000, message='O número máximo de amostras é 40000.')], verbose_name='Total de Amostras')),
                ('email', models.EmailField(max_length=254, verbose_name='Email para Envio')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=plate_app.models.pdf_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projeto de Placas',
                'verbose_name_plural': 'Projetos de Placas',
                'unique_together': {('empresa', 'projeto')},
            },
        ),
    ]
